export const FETCHING_QUESTION_REQUEST = 'FETCHING_QUESTION_REQUEST'; 
export const FETCHING_QUESTION_SUCCESS = 'FETCHING_QUESTION_SUCCESS'; 
export const FETCHING_QUESTION_FAILURE = 'FETCHING_QUESTION_FAILURE'; 
export const FETCHING_QUESTIONQUIZ_REQUEST = 'FETCHING_QUESTIONQUIZ_REQUEST'; 
export const FETCHING_QUESTIONQUIZ_SUCCESS = 'FETCHING_QUESTIONQUIZ_SUCCESS'; 
export const FETCHING_QUESTIONQUIZ_FAILURE = 'FETCHING_QUESTIONQUIZ_FAILURE'; 